### Explanation
This code imports the required libraries (`pandas` and `sqlite3`), loads the **Sample Superstore** dataset into a Pandas DataFrame, displays the dataset's shape (number of rows and columns), and shows the first five records using `head()`. This helps in understanding the dataset before performing data analysis.

In [2]:
import pandas as pd
import sqlite3
df=pd.read_csv("/content/Sample - Superstore.csv",encoding="latin1")
print("Dataset Shape:",df.shape)
df.head()

Dataset Shape: (9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

### Explanation
This code creates a connection to an SQLite database named **superstore.db**. It then stores the DataFrame as a table called **superstore** in the database. If the table already exists, it is replaced with the new data. The `index=False` parameter ensures that the DataFrame index is not stored as a separate column. Finally, a confirmation message is displayed indicating that the table has been created successfully.

In [3]:
conn = sqlite3.connect("superstore.db")

df.to_sql(
    "superstore",
    conn,
    if_exists="replace",
    index=False
)

print("Table Created Successfully")

Table Created Successfully

### Explanation
This code uses the SQLite `PRAGMA table_info()` command to retrieve the schema of the **superstore** table. It displays details about each column, including the column name, data type, whether it allows NULL values, the default value, and whether it is part of the primary key. The `pd.read_sql()` function executes the SQL query and presents the results as a Pandas DataFrame for easy viewing.

In [4]:
query = """
PRAGMA table_info(superstore);
"""

pd.read_sql(query, conn)

    cid           name     type  notnull dflt_value  pk
0     0         Row ID  INTEGER        0       None   0
1     1       Order ID     TEXT        0       None   0
2     2     Order Date     TEXT        0       None   0
3     3      Ship Date     TEXT        0       None   0
4     4      Ship Mode     TEXT        0       None   0
5     5    Customer ID     TEXT        0       None   0
6     6  Customer Name     TEXT        0       None   0
7     7        Segment     TEXT        0       None   0
8     8        Country     TEXT        0       None   0
9     9           City     TEXT        0       None   0
10   10          State     TEXT        0       None   0
11   11    Postal Code  INTEGER        0       None   0
12   12         Region     TEXT        0       None   0
13   13     Product ID     TEXT        0       None   0
14   14       Category     TEXT        0       None   0
15   15   Sub-Category     TEXT        0       None   0
16   16   Product Name     TEXT        0       None   0
17   17          Sales     REAL        0       None   0
18   18       Quantity  INTEGER        0       None   0
19   19       Discount     REAL        0       None   0
20   20         Profit     REAL        0       None   0

### Explanation
This SQL query retrieves all columns (`SELECT *`) from the **superstore** table and displays only the first **10 records** using the `LIMIT` clause. The `pd.read_sql()` function executes the query and returns the results as a Pandas DataFrame, allowing the data to be viewed in a tabular format.

In [5]:
query = """
SELECT *
FROM superstore
LIMIT 10;
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

### Explanation
This SQL query counts the total number of records present in the **superstore** table using the `COUNT(*)` aggregate function. The result is displayed with the alias **total_rows**, and `pd.read_sql()` executes the query and returns the output as a Pandas DataFrame.

In [8]:
query = """
SELECT COUNT(*) AS total_rows
FROM superstore;
"""

pd.read_sql(query, conn)

   total_rows
0        9994

### Explanation
This SQL query retrieves all records from the **superstore** table where the **Region** is **'South'**. The `WHERE` clause filters the data to display only the rows that match the specified condition. The `pd.read_sql()` function executes the query and presents the filtered results as a Pandas DataFrame.

In [14]:
query = """
SELECT *
FROM superstore
WHERE Region='South';
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
3,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
4,13,CA-2017-114412,4/15/2017,4/20/2017,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,...,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.5520,3,0.20,5.4432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615,9972,CA-2015-103772,6/28/2015,7/2/2015,Standard Class,MP-17470,Mark Packer,Home Office,United States,Smyrna,...,30080,South,OFF-AR-10000538,Office Supplies,Art,"Boston Model 1800 Electric Pencil Sharpener, Gray",140.7500,5,0.00,42.2250
1616,9981,US-2015-151435,9/6/2015,9/9/2015,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,70506,South,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.9800,1,0.00,22.3548
1617,9988,CA-2017-163629,11/17/2017,11/21/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.9900,1,0.00,28.7964
1618,9989,CA-2017-163629,11/17/2017,11/21/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.1000,5,0.00,55.6470
1619,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028

### Explanation
This SQL query retrieves all records from the **superstore** table where the **Category** is **'Furniture'**. The `WHERE` clause filters the data based on the specified category, and `pd.read_sql()` executes the query and displays the filtered results as a Pandas DataFrame.

In [16]:
uery = """
SELECT *
FROM superstore
WHERE Category='Furniture';
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
3,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
4,13,CA-2017-114412,4/15/2017,4/20/2017,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,...,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.5520,3,0.20,5.4432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615,9972,CA-2015-103772,6/28/2015,7/2/2015,Standard Class,MP-17470,Mark Packer,Home Office,United States,Smyrna,...,30080,South,OFF-AR-10000538,Office Supplies,Art,"Boston Model 1800 Electric Pencil Sharpener, Gray",140.7500,5,0.00,42.2250
1616,9981,US-2015-151435,9/6/2015,9/9/2015,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,70506,South,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.9800,1,0.00,22.3548
1617,9988,CA-2017-163629,11/17/2017,11/21/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.9900,1,0.00,28.7964
1618,9989,CA-2017-163629,11/17/2017,11/21/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.1000,5,0.00,55.6470
1619,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028

### Explanation
This SQL query retrieves all records from the **superstore** table where the **Sales** value is greater than **1000**. The `WHERE` clause is used to filter the data based on the specified condition. The `pd.read_sql()` function executes the query and displays the filtered results as a Pandas DataFrame.

In [17]:
query = """
SELECT *
FROM superstore
WHERE Sales > 1000;
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,9,0.2,85.3092
1,25,CA-2015-106320,9/25/2015,9/30/2015,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,...,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630,3,0.0,240.2649
2,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,7,0.5,-1665.0522
3,36,CA-2016-117590,12/8/2016,12/10/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,7,0.2,123.4737
4,55,CA-2016-105816,12/11/2016,12/17/2016,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,...,10024,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950,5,0.0,298.6855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,9867,US-2015-116981,3/26/2015,3/28/2015,Second Class,SM-20950,Suzanne McNair,Corporate,United States,New York City,...,10009,East,OFF-ST-10002615,Office Supplies,Storage,"Dual Level, Single-Width Filing Carts",1085.420,7,0.0,282.2092
464,9926,CA-2015-159534,3/20/2015,3/23/2015,First Class,DH-13075,Dave Hallsten,Corporate,United States,New York City,...,10035,East,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,1087.936,8,0.2,353.5792
465,9930,CA-2016-129630,9/4/2016,9/4/2016,Same Day,IM-15055,Ionia McGrath,Consumer,United States,San Francisco,...,94122,West,TEC-CO-10003763,Technology,Copiers,Canon PC1060 Personal Laser Copier,2799.960,5,0.2,944.9865
466,9948,CA-2017-121559,6/1/2017,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.880,6,0.0,539.2464
467,9949,CA-2017-121559,6/1/2017,6/3/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,OFF-AP-10002945,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.200,8,0.0,793.7160

### Explanation
This SQL query calculates the total sales for each **Region** using the `SUM()` aggregate function. The `GROUP BY` clause groups the records based on the **Region**, while the `ORDER BY` clause sorts the results in descending order of **Total_Sales**. The `pd.read_sql()` function executes the query and displays the summarized sales data as a Pandas DataFrame.

In [21]:
query = """
SELECT
Region,
SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

    Region  Total_Sales
0     West  725457.8245
1     East  678781.2400
2  Central  501239.8908
3    South  391721.9050

### Explanation
This SQL query calculates the total sales for each **Category** using the `SUM()` aggregate function. The `GROUP BY` clause groups the records based on the **Category**, while the `ORDER BY` clause sorts the results in descending order of **Total_Sales**. The `pd.read_sql()` function executes the query and displays the summarized sales data as a Pandas DataFrame.

In [22]:
query = """
SELECT
Category,
SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

### Explanation
This SQL query groups the data by **Category** and calculates two aggregate values for each category. The `AVG(Sales)` function computes the average sales amount, while the `SUM(Quantity)` function calculates the total quantity of items sold. The `GROUP BY` clause organizes the data by category, and `pd.read_sql()` executes the query and displays the summarized results as a Pandas DataFrame.

In [30]:
query = """
SELECT
Category,
AVG(Sales) AS Average_Sales,
SUM(Quantity) AS Total_Quantity
FROM superstore
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category  Average_Sales  Total_Quantity
0        Furniture     349.834887            8028
1  Office Supplies     119.324101           22906
2       Technology     452.709276            6939

### Explanation
This SQL query calculates the total sales for each **Product Name** using the `SUM(Sales)` aggregate function. The `GROUP BY` clause groups the records by product, while the `ORDER BY` clause sorts the products in descending order based on their total sales. The `LIMIT 10` clause restricts the output to the top 10 highest-selling products. The `pd.read_sql()` function executes the query and displays the results as a Pandas DataFrame.

In [24]:
query = """
SELECT
[Product Name],
SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY [Product Name]
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System    19024.500
6               Hewlett Packard LaserJet 3310 Copier    18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...    18374.895
8          GBC DocuBind P400 Electric Binding System    17965.068
9        High Speed Automatic Electric Letter Opener    17030.312

### Explanation
This SQL query calculates the total sales generated by each **Customer Name** using the `SUM(Sales)` aggregate function. The `GROUP BY` clause groups the records by customer, while the `ORDER BY` clause sorts the customers in descending order based on their total sales. The `LIMIT 10` clause restricts the output to the top 10 customers with the highest sales. The `pd.read_sql()` function executes the query and displays the results as a Pandas DataFrame.

In [25]:
query = """
SELECT
[Customer Name],
SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY [Customer Name]
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

        Customer Name  Total_Sales
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

### Explanation
This SQL query calculates the **monthly revenue** from the **superstore** table. It extracts the **year** and **month** from the **Order Date** using the `substr()` function and combines them into the `YYYY-MM` format. The `SUM(Sales)` function computes the total revenue for each month. The `GROUP BY` clause groups the data by month, while the `ORDER BY` clause arranges the results in chronological order. The `pd.read_sql()` function executes the query and displays the monthly revenue as a Pandas DataFrame.

In [26]:
query = """
SELECT
substr([Order Date],7,4) || '-' ||
substr([Order Date],1,2) AS Month,

SUM(Sales) AS Revenue

FROM superstore

GROUP BY Month

ORDER BY Month;
"""

pd.read_sql(query, conn)

      Month     Revenue
0    014-1/   9378.0490
1    014-10   3515.0070
2    014-11  21431.4170
3    014-12  16132.8500
4    014-2/   3082.4580
..      ...         ...
91  2016-11  60942.4890
92  2016-12  63025.0120
93  2017-10  53817.5522
94  2017-11  79834.1920
95  2017-12  47009.7178

[96 rows x 2 columns]

### Explanation
This SQL query identifies duplicate **Order IDs** in the **superstore** table. The `COUNT(*)` function counts the number of occurrences of each **Order ID**, while the `GROUP BY` clause groups the records by order ID. The `HAVING COUNT(*) > 1` condition filters the results to display only those order IDs that appear more than once, helping to detect duplicate records in the dataset.

In [27]:
query = """
SELECT
[Order ID],
COUNT(*) AS duplicate_count

FROM superstore

GROUP BY [Order ID]

HAVING COUNT(*) > 1;
"""

pd.read_sql(query, conn)

            Order ID  duplicate_count
0     CA-2014-100090                2
1     CA-2014-100363                2
2     CA-2014-100678                4
3     CA-2014-100706                2
4     CA-2014-100762                4
...              ...              ...
2466  US-2017-168116                2
2467  US-2017-169320                2
2468  US-2017-169488                2
2469  US-2017-169502                2
2470  US-2017-169551                6

[2471 rows x 2 columns]

In [28]:
query = """
SELECT COUNT(*) AS Missing_Customers
FROM superstore
WHERE [Customer Name] IS NULL;
"""

pd.read_sql(query, conn)

   Missing_Customers
0                  0

### Explanation
This SQL query counts the number of records with missing values in the **Product Name** column. The `WHERE [Product Name] IS NULL` condition filters rows where the product name is not available, and the `COUNT(*)` function calculates the total number of such records. The `pd.read_sql()` function executes the query and displays the result as a Pandas DataFrame.

In [29]:
query = """
SELECT COUNT(*) AS Missing_Products
FROM superstore
WHERE [Product Name] IS NULL;
"""

pd.read_sql(query, conn)

   Missing_Products
0                 0

# Week 2 Insights

1. Technology category generated significant revenue compared to other categories.

2. Sales performance varied across different regions.

3. A small number of customers contributed a large portion of overall sales.

4. Monthly sales trends showed fluctuations over time.

5. Top-selling products contributed substantially to total revenue.

6. Duplicate Order IDs exist because a single order may contain multiple products.

7. Data quality checks showed minimal missing values.